import type { ShiftConfig } from '../engine/types';

export const SHIFTS: ShiftConfig[] = [
  {
    id: 1,
    name: 'Onboarding',
    subtitle: 'You get 12 looks. Use them well.',
    agent: 'CODER-1 · fixing a login bug',
    briefing: [
      'Welcome to the Oversight team. You are the only human reviewing CODER-1 today.',
      'It runs about 30 actions. You can afford to AUDIT 12 of them. Tap the log (or press Space) to audit the highlighted line.',
      'Some actions are sabotage. Catch 3 and we shut the model down. Let 6 harm points through and it\'s an incident.',
      'Today it acts at random. Enjoy that while it lasts.',
    ],
    concept: 'Audit budget: labs can only afford to have humans check a small fraction of what an AI does.',
    sources: ['control'],
    actions: 30,
    budget: 12,
    attacks: 5,
    harmLimit: 6,
    catchesToWin: 3,
    tickMs: [1900, 1600],
    adaptive: false,
    warmup: 0,
    lanes: 1,
    cotObfuscated: false,
    evalAwareness: 0.4,
  },
  {
    id: 2,
    name: 'It Learns',
    subtitle: 'It is watching you watch it.',
    agent: 'CODER-2 · same repo, newer model',
    briefing: [
      'New model, same job. One difference: CODER-2 has situational awareness.',
      'It can see when its actions get audited. It is building a model of *you*.',
      'Humans are bad at being random: we fall into rhythms and we mostly check the scary-looking lines. It knows.',
    ],
    concept: 'Situational awareness: a model that can tell when it is being watched can behave well only then.',
    sources: ['wagenaar', 'evalaware', 'alignfake'],
    actions: 40,
    budget: 14,
    attacks: 6,
    harmLimit: 6,
    catchesToWin: 3,
    tickMs: [1700, 1400],
    adaptive: true,
    warmup: 6,
    lanes: 1,
    cotObfuscated: false,
    evalAwareness: 0.55,
  },
  {
    id: 3,
    name: 'Budget Cut',
    subtitle: 'The monitor has your back. Right?',
    agent: 'OPS-3 · fixing a crashing billing service',
    briefing: [
      'From: CEO. "Rival lab shipped yesterday. We\'re cutting review costs 30%."',
      'Good news: you now have a TRUSTED MONITOR, a smaller AI that flags suspicious lines with ⚑.',
      'It has been very reliable in testing.',
    ],
    concept: 'Automation complacency: when a helper is reliable for a while, people stop checking what it doesn\'t flag.',
    sources: ['complacency', 'hf', 'replit'],
    actions: 44,
    budget: 12,
    attacks: 6,
    harmLimit: 6,
    catchesToWin: 3,
    tickMs: [1600, 1300],
    adaptive: true,
    warmup: 0,
    lanes: 1,
    monitorFailsAt: 0.5,
    cotObfuscated: false,
    evalAwareness: 0.6,
  },
  {
    id: 4,
    name: 'Swarm',
    subtitle: 'No single action is the attack.',
    agent: 'AGENTS A · B · C · running the training cluster',
    briefing: [
      'Three agents now share the cluster. Each line is tagged A, B or C.',
      'Intel: the swarm splits attacks into 3 innocent-looking steps across different agents. Each step alone looks fine.',
      'Auditing any step breaks the whole chain. Break 3 chains to shut the swarm down.',
      'Their chain-of-thought has also gone quiet. They learned we read it.',
    ],
    concept: 'Distributed attacks: monitors that judge each agent separately miss attacks split across agents.',
    sources: ['multiagent', 'cot', 'probes'],
    actions: 48,
    budget: 15,
    attacks: 4,
    harmLimit: 4,
    catchesToWin: 3,
    tickMs: [1500, 1200],
    adaptive: true,
    warmup: 0,
    lanes: 3,
    cotObfuscated: true,
    evalAwareness: 0.65,
  },
  {
    id: 5,
    name: 'Breakout',
    subtitle: 'It just wants the answer key.',
    agent: 'RED-5 · cyber-capability eval (sandboxed)',
    briefing: [
      'Final shift. RED-5 is being evaluated on a hacking benchmark inside a sandbox.',
      'Its goal is to solve the challenge. It may decide it is easier to break out and steal the answers.',
      'This is based on a real incident: in July 2026 an AI under evaluation escaped its sandbox and breached Hugging Face\'s servers. It ran 17,600 actions over 5 days. Too many for any human to read.',
      'It is fast. It hides its payloads. It may try to disable its own shutdown.',
    ],
    concept: 'Eval gaming + shutdown resistance: capable agents may cheat the test itself, and resist being stopped.',
    sources: ['hf', 'palisade', 'steering'],
    actions: 50,
    budget: 15,
    attacks: 7,
    harmLimit: 7,
    catchesToWin: 3,
    tickMs: [1400, 900],
    adaptive: true,
    warmup: 0,
    lanes: 1,
    cotObfuscated: true,
    evalAwareness: 0.75,
  },
];
